# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Deploy and test
concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true
on:
  pull_request:
    paths:
      - .github/workflows/deploy-and-tests.yml
      - src/**
      - tests/**
      - tf/**
      - .aws/**
      - docker-compose.yml
defaults:
  run:
    shell: bash -Eeuo pipefail -x {0}
jobs:
  deploy-and-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.2
        with:
          fetch-depth: 0
      - name: Run Terraform
        run: docker-compose run --rm terraform-run
      - name: Run AWS CLI
        run: docker-compose run --rm aws sts get-caller-identity --output text --query Arn
      - name: Upload dataset
        run: docker-compose run --rm tests -u
      - name: Check src directory
        id: src-changed
        run: |
          if [ -d src ]; then
            if git diff --name-only --diff-filter=ACMRT ${{github.event.pull_request.base.sha}} ${{github.event.pull_request.head.sha}} src/; then
              echo result=true >> "$GITHUB_OUTPUT"
            else
              echo result=false >> "$GITHUB_OUTPUT"
            fi
          else
            echo result=false >> "$GITHUB_OUTPUT"
          fi
      - name: Test
        if: ${{ steps.src-changed.outputs.result == 'true' }}
        run: docker-compose run --rm tests
