# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Semantic PR
concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true
on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize
jobs:
  semantic-pr:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    permissions:
      statuses: write
      pull-requests: read
    steps:
      - name: Semantic pull-request
        uses: amannn/action-semantic-pull-request@c24d6dd07c69e0826c52021944f216b2e3192535 # v5.5.0
        with:
          requireScope: false
          wip: true
          validateSingleCommit: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
